void f_with_exceptions(void);
